### ISSUE TITLE
remove codes that are not used in this program

### ISSUE THREAD

**Issue by jianwuwang** [big-data-lab-umbc/MODIS-Aggregation#1]
https://github.com/big-data-lab-umbc/MODIS-Aggregation/blob/c9c7d195fc0b34f0b35962419f69412de85a7458/MODIS_CloudFraction_Dask_XArray_GroupBy.py#L70

**Comment by saviokay** [comment]
I have updated the code to reflect this issue in the latest commit. 
Removed bit0 and bit12 from the code and made the required changes further into the program.
Closing the Issue.
